### ISSUE TITLE
HTTP/3

### ISSUE THREAD

**Issue by martinthomson** [chris-wood/quips-workshop#1]
The summary here doesn't say whether HTTP/3 is in scope. It probably should.

I tend to lead toward discouraging papers on h3. There is some value in studying the security of things like QPACK, but that is fairly narrow and most of the scrutiny here would likely be much more general than is ideal.

**Comment by chris-wood** [comment]
Good catch -- I agree! I'll try to work it in with Antoine.

**Comment by ad-l** [comment]
I agree that we should consider the security impact of QUIC for the application. I added a bullet point in #2

**Comment by chris-wood** [comment]
Fixed in #2.
